In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
import sklearn.datasets
import datetime
import time
from pandas import Series, DataFrame
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

earthquakes = pd.read_table('database.csv', sep = ",")
pd.set_option('display.max_columns', 21)

In [38]:


timestamp = []
for d, t in zip(earthquakes['Date'], earthquakes['Time']):
    try:
        ts = datetime.datetime.strptime(d+' '+t, '%m/%d/%Y %H:%M:%S')
        timestamp.append(time.mktime(ts.timetuple()))
    except ValueError:
        # print('ValueError')
        timestamp.append('ValueError')
timeStamp = pd.Series(timestamp)
earthquakes['Timestamp'] = timeStamp.values
final_data = earthquakes.drop(['Date', 'Time','ID','Type','Source','Root Mean Square','Depth Error','Depth Seismic Stations','Location Source','Magnitude Seismic Stations','Magnitude Source','Status','Horizontal Error','Magnitude Error','Horizontal Distance'], axis=1)
final_data = final_data[final_data.Timestamp != 'ValueError']
final_data

,Latitude,Longitude,Depth,Magnitude,Magnitude Type,Azimuthal Gap,Timestamp
0,19.2460,145.6160,131.60,6.0,MW,NaN,-1.57605e+08
1,1.8630,127.3520,80.00,5.8,MW,NaN,-1.57441e+08
2,-20.5790,-173.9720,20.00,6.2,MW,NaN,-1.5733e+08
3,-59.0760,-23.5570,15.00,5.8,MW,NaN,-1.57069e+08
4,11.9380,126.4270,15.00,5.8,MW,NaN,-1.57001e+08
...,...,...,...,...,...,...,...
23407,38.3917,-118.8941,12.30,5.6,ML,42.47,1.48294e+09
23408,38.3777,-118.8957,8.80,5.5,ML,48.58,1.48294e+09
23409,36.9179,140.4262,10.00,5.9,MWW,91.00,1.48295e+09
23410,-9.0283,118.6639,79.00,6.3,MWW,26.00,1.48308e+09
23411,37.3973,141.4103,11.94,5.5,MB,97.00,1.48315e+09

In [61]:
features = ['Latitude','Longitude','Timestamp']
target = ['Magnitude','Depth']
X_train,X_test,y_train,y_test = train_test_split(final_data[features],final_data[target],test_size=0.2)

In [62]:
model = RandomForestRegressor(n_estimators = 1000,max_depth=10)
#model = LinearRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.38026502511906096